name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_package:
    name: BUILD-JOB
    runs-on: ubuntu-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: BUILD
        run: npm run build

      - name: Test
        run: npm test
