name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - master
      
      
jobs:
  build_and_package:
    name: BUILD-JOB
    runs-on: ubuntu-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: BUILD
        run: npm ci

      - name: Test
        run: echo "code is tested!"


